### ISSUE TITLE
Is there any doc for the motivation/ideas/designs?

### ISSUE THREAD

**Issue by anqur** [thautwarm/DIO.jl#3]
* I'm kinda curious about how Julia can interact with CPython runtime, and back it with its JIT compiler
* My stupid ugly intuition is that DIO.jl declares the same binary structures to CPython's, and Julia JIT will do the bunch of compilation on the fly, is that right?

**Comment by anqur** [comment]
Some references in Twitter:

* https://twitter.com/thautwarm/status/1356752942137675776
* https://twitter.com/thautwarm/status/1351485093576024066

Closing this for dumb thoughts.

**Comment by thautwarm** [comment]
Julia can make c functions at runtime, without calling `gcc` or other background compilers, which significantly reduces the latency.

The c functions made by Julia will be passed back to Python, and is wrapped as a python function using `PyCFunction_NewEx` C API.

We don't actually need Julia's JIT features. Everything is `PyObject*`(PyPtr). We just use Julia as a runtime compiler.

**Comment by thautwarm** [comment]
As a friend, I do want to have a personal talk with you now. However things are now quite busy. I need to polish the paper and prepare a lot for the talk. The polished paper around 2/19, and I will have much time after 2/19. We can start designing the roadmap since that.

**Comment by anqur** [comment]
> As a friend, I do want to have a personal talk with you now. However things are now quite busy. I need to polish the paper and prepare a lot for the talk. The polished paper around 2/19, and I will have much time after 2/19. We can start designing the roadmap since that.

Yes! And I totally agree with you! I just created this issue before I noticed that you would give a talk on this (I’ve been away from Twitter for days). One of the best ways to present the ideas is just a presentation. Can’t wait to see you there (online)! :D
